import type { SQLiteDatabase } from 'expo-sqlite';
import type { CategoryTotal, Event, MonthlySummary, Todo, Transaction, TransactionType } from '@/types/models';
import { isoNow } from '@/lib/date';

type EventRow = Omit<Event, 'isAllDay'> & { isAllDay: number };
type TodoRow = Omit<Todo, 'completed'> & { completed: number };
const mapEvent = (row: EventRow): Event => ({ ...row, isAllDay: Boolean(row.isAllDay) });
const mapTodo = (row: TodoRow): Todo => ({ ...row, completed: Boolean(row.completed) });

export async function getEvents(db: SQLiteDatabase, start?: string, end?: string) { const rows = start && end ? await db.getAllAsync<EventRow>('SELECT * FROM events WHERE date BETWEEN ? AND ? ORDER BY date ASC, startTime ASC, id ASC', start, end) : await db.getAllAsync<EventRow>('SELECT * FROM events ORDER BY date ASC, startTime ASC, id ASC'); return rows.map(mapEvent); }
export async function getEvent(db: SQLiteDatabase, id: number) { const row = await db.getFirstAsync<EventRow>('SELECT * FROM events WHERE id = ?', id); return row ? mapEvent(row) : null; }
export async function saveEvent(db: SQLiteDatabase, data: Omit<Event, 'id' | 'createdAt' | 'updatedAt'>, id?: number) { const now = isoNow(); if (id) { await db.runAsync('UPDATE events SET title=?, date=?, startTime=?, endTime=?, isAllDay=?, category=?, location=?, memo=?, budget=?, updatedAt=? WHERE id=?', data.title, data.date, data.startTime, data.endTime, data.isAllDay ? 1 : 0, data.category, data.location, data.memo, data.budget, now, id); return id; } const result = await db.runAsync('INSERT INTO events (title,date,startTime,endTime,isAllDay,category,location,memo,budget,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)', data.title, data.date, data.startTime, data.endTime, data.isAllDay ? 1 : 0, data.category, data.location, data.memo, data.budget, now, now); return result.lastInsertRowId; }
export async function deleteEvent(db: SQLiteDatabase, id: number) { await db.runAsync('DELETE FROM events WHERE id = ?', id); }
export async function getTodos(db: SQLiteDatabase, onlyOpen = false) { const rows = onlyOpen ? await db.getAllAsync<TodoRow>('SELECT * FROM todos WHERE completed=0 ORDER BY CASE WHEN dueDate IS NULL THEN 1 ELSE 0 END, dueDate ASC, id DESC') : await db.getAllAsync<TodoRow>('SELECT * FROM todos ORDER BY completed ASC, CASE WHEN dueDate IS NULL THEN 1 ELSE 0 END, dueDate ASC, id DESC'); return rows.map(mapTodo); }
export async function getTodo(db: SQLiteDatabase, id: number) { const row = await db.getFirstAsync<TodoRow>('SELECT * FROM todos WHERE id = ?', id); return row ? mapTodo(row) : null; }
export async function saveTodo(db: SQLiteDatabase, data: Omit<Todo, 'id' | 'createdAt' | 'updatedAt' | 'completed'> & { completed?: boolean }, id?: number) { const now = isoNow(); if (id) { await db.runAsync('UPDATE todos SET title=?, dueDate=?, category=?, priority=?, memo=?, updatedAt=? WHERE id=?', data.title, data.dueDate, data.category, data.priority, data.memo, now, id); return id; } const result = await db.runAsync('INSERT INTO todos (title,dueDate,category,priority,memo,completed,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)', data.title, data.dueDate, data.category, data.priority, data.memo, data.completed ? 1 : 0, now, now); return result.lastInsertRowId; }
export async function toggleTodo(db: SQLiteDatabase, id: number, completed: boolean) { await db.runAsync('UPDATE todos SET completed=?, updatedAt=? WHERE id=?', completed ? 1 : 0, isoNow(), id); }
export async function deleteTodo(db: SQLiteDatabase, id: number) { await db.runAsync('DELETE FROM todos WHERE id = ?', id); }
export async function getTransactions(db: SQLiteDatabase, start?: string, end?: string) { const query = `SELECT t.*, e.title as eventTitle FROM transactions t LEFT JOIN events e ON e.id=t.eventId ${start && end ? 'WHERE t.date BETWEEN ? AND ?' : ''} ORDER BY t.date DESC, t.id DESC`; return start && end ? db.getAllAsync<Transaction>(query, start, end) : db.getAllAsync<Transaction>(query); }
export async function getTransaction(db: SQLiteDatabase, id: number) { return db.getFirstAsync<Transaction>('SELECT t.*, e.title as eventTitle FROM transactions t LEFT JOIN events e ON e.id=t.eventId WHERE t.id=?', id); }
export async function saveTransaction(db: SQLiteDatabase, data: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt' | 'eventTitle'>, id?: number) { const now = isoNow(); if (id) { await db.runAsync('UPDATE transactions SET type=?, amount=?, date=?, category=?, paymentMethod=?, shopName=?, memo=?, eventId=?, updatedAt=? WHERE id=?', data.type, data.amount, data.date, data.category, data.paymentMethod, data.shopName, data.memo, data.eventId, now, id); return id; } const result = await db.runAsync('INSERT INTO transactions (type,amount,date,category,paymentMethod,shopName,memo,eventId,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?)', data.type, data.amount, data.date, data.category, data.paymentMethod, data.shopName, data.memo, data.eventId, now, now); return result.lastInsertRowId; }
export async function deleteTransaction(db: SQLiteDatabase, id: number) { await db.runAsync('DELETE FROM transactions WHERE id=?', id); }
export async function getMonthlySummary(db: SQLiteDatabase, start: string, end: string): Promise<MonthlySummary> { const rows = await db.getAllAsync<{ type: TransactionType; total: number | null }>('SELECT type, SUM(amount) as total FROM transactions WHERE date BETWEEN ? AND ? GROUP BY type', start, end); return { income: rows.find((row) => row.type === 'income')?.total ?? 0, expense: rows.find((row) => row.type === 'expense')?.total ?? 0 }; }
export async function getCategoryTotals(db: SQLiteDatabase, start: string, end: string): Promise<CategoryTotal[]> { return db.getAllAsync<CategoryTotal>('SELECT category, SUM(amount) as total FROM transactions WHERE type="expense" AND date BETWEEN ? AND ? GROUP BY category ORDER BY total DESC', start, end); }
export async function getEventSpent(db: SQLiteDatabase, eventId: number) { const row = await db.getFirstAsync<{ total: number | null }>('SELECT SUM(amount) as total FROM transactions WHERE eventId=? AND type="expense"', eventId); return row?.total ?? 0; }
export async function getMonthlyBudget(db: SQLiteDatabase) { const row = await db.getFirstAsync<{ value: string | null }>('SELECT value FROM settings WHERE key="monthlyBudget"'); return row?.value ? Number(row.value) : 0; }
export async function setMonthlyBudget(db: SQLiteDatabase, value: number) { await db.runAsync('INSERT INTO settings (key,value) VALUES ("monthlyBudget", ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value', String(value)); }
